### ISSUE TITLE
Can't `npm start` :  Unable to load plugin 'enhance/arc-plugin-enhance': Cannot find module 'node:fs'

### ISSUE THREAD

**Issue by wstewarttennes** [enhance-dev/enhance-music#3]
1. ran `npm install` to install packages
2. ran `npm start`
3. received the following output
```
❯ npm start

> enhance-music@1.1.0 start /Users/westonstewart-tennes/dev/dijondreams/services/enhance-music
> npx enhance dev

Error: Plugin error:
- Unable to load plugin 'enhance/arc-plugin-enhance': Cannot find module 'node:fs'
```

wondering if there's a recommended node version i should be running?

**Comment by wstewarttennes** [comment]
Node: I was able to fix this by upgrading Node to 18.18.0.  Closing this because i think that's fine but would be great to have a minimum Node version listed!

**Comment by tbeseda** [comment]
Glad you got it working @wstewarttennes 👍 -- we'll add that to our list of items when documenting demos like this. Thanks
Just FYI, Node 16 has left maintenance mode and is end-of-life as of Sept 11. Highly recommend updating old apps if at all possible.
https://nodejs.org/en/blog/announcements/nodejs16-eol

**Comment by macdonst** [comment]
@tbeseda we should add an engines section to the package.json.
